services:
  - type: web
    name: vidfetch-backend
    env: node
    plan: free
    buildCommand: |
      npm install
      apt-get update
      apt-get install -y ffmpeg
      curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
      chmod a+rx /usr/local/bin/yt-dlp
    startCommand: node server.js
